package com.example.activityapp.controllers;

import com.example.activityapp.exceptions.ActivityNotFoundException;
import com.example.activityapp.exceptions.MissingParameterException;
import com.example.activityapp.models.UserActivity;
import com.example.activityapp.services.ActivityService;
import com.example.activityapp.services.GptService;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.util.ObjectUtils;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

/**
 * Constructor for the ActivityController class
 */
@RestController
@RequestMapping(path = "/")
public class ActivityController {

  @Autowired
  private ActivityService activityService;

  @Autowired
  private GptService gptService;

  public ActivityController(ActivityService activityService, GptService gptService) {
    this.activityService = activityService;
    this.gptService = gptService;
  }

  @GetMapping(value = "/")
  public String getActivityByDate(){
    return "ready to receive requests";
  }

  /**
   * Returns a user activity based on the date and type if the type of activity if provided. Else,
   * it returns the activity based on the date only.
   * @param date a string that represents the date the activity occurred
   * @param type a string that represents the type of activity
   * @return a user activity based on the date
   */
  @GetMapping(value = "/byDate/{date}")
  public UserActivity getActivityByDate(@PathVariable String date, @RequestParam(value = "type", required = false) String type){
    if (!ObjectUtils.isEmpty(type)){
      return activityService.getActivityByDateAndType(date, type);
    }
    if (!ObjectUtils.isEmpty(date)) {
      return activityService.findByDate(date);
    }
    throw new ActivityNotFoundException(String.format("Activity with date %s and type %s not found", date, type));
  }

  /**
   * Returns a hashmap containing the daily calories burned and a response generated by a separate
   * GptService.
   * @param date a string that represents the date the activity occurred
   * @return a hashmap containing the daily calories burned and a response generated by a separate
   */
  @GetMapping(value = "/byDate/{date}/calories")
  public Map<String, Object> getActivityByDate(@PathVariable String date){
    if (!ObjectUtils.isEmpty(date)) {
      int dailyCalories = activityService.getActivityCaloriesByDate(date);
      String gptResponse = gptService.getChatGptResponse(dailyCalories);
      Map<String, Object> response = new HashMap<>();
      response.put("calories", dailyCalories);
      response.put("ChatGPTResponse", gptResponse);
      return response;
    }
    throw new MissingParameterException("Missing required parameter 'date'");
  }

//  @GetMapping(value = "/assistant")
//  public String getAssistantMessage(@RequestParam int dailyCalories, @RequestParam String question){
//    if (!ObjectUtils.isEmpty(dailyCalories) && !ObjectUtils.isEmpty(question)) {
//      String gptResponse = gptService.getChatGptResponse(dailyCalories, question);
////      Map<String, Object> response = new HashMap<>();
////      response.put("calories", dailyCalories);
////      response.put("ChatGPTResponse", gptResponse);
//      return gptResponse;
//    }
//    throw new MissingParameterException("Missing required parameters");
//  }


//  @CrossOrigin(origins = "http://localhost:3000", methods = {RequestMethod.GET, RequestMethod.POST})

  /**
   * Returns a SseEmitter object that sends the response to the client.
   * @param dailyCalories an integer that represents the daily calories burned
   * @param question a string that represents a question that the client wants to ask the assistant
   * @return a SseEmitter object that sends the response to the client
   */
  @GetMapping(value = "/assistant", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
  public SseEmitter getAssistantMessage(@RequestParam int dailyCalories, @RequestParam String question) {
    if (!ObjectUtils.isEmpty(dailyCalories) && !ObjectUtils.isEmpty(question)) {
      SseEmitter gptResponse = gptService.getChatGptResponse(dailyCalories, question);
      return gptResponse;
    }
    throw new MissingParameterException("Missing required parameters");
  }

  /**
   * If the payload is not null, the insertActivity method is called to insert the user activity
   * into the database.
   * @param payload a UserActivity object that provides information about the user activity to be
   *                inserted into the database
   */
  @PostMapping("/insertActivity")
  public void insertActivity(@RequestBody UserActivity payload) {
    if (payload != null) {
      activityService.insertActivity(payload);
      return;
    }
    //throw new ActivityNotFoundException("Not a valid payload.");
  }

  /**
   * Returns a list of user activities in the form of a JSON array of userActivity objects.
   * @param startDateString a string that represents the start date of the activity period for
   *                        which the user activities should be retrieved.
   * @param endDateString a string that represents the end date of the activity period for which
   *                      the user activities should be retrieved.
   * @return a list of user activities
   */
  @GetMapping(value = "/byDate/{start}/{end}")
  public List<UserActivity> getActivityByDateBetweenT(@PathVariable("start") String startDateString,
      @PathVariable("end") String endDateString){
    List<UserActivity> userActivities = activityService.getActivitiesBetweenDates(startDateString, endDateString);
    return userActivities;
  }

  /**
   * Returns a user activity in the form of a JSON object.
   * @param date a string that represents the date the activity occurred
   * @param type a string that represents the type of activity
   * @return a user activity in the form of a JSON object.
   */
  @GetMapping(value = "/byType/{date}/{type}")
  public UserActivity getActivityByType(@PathVariable("date") String date, @PathVariable("type") String type){
    UserActivity userActivity = activityService.getActivityByDateAndType(date, type);
    return userActivity;
  }

  /**
   * Returns a list of user activities in the form of a JSON array of userActivity objects.
   * @return a list of user activities in the form of a JSON array of userActivity objects
   */
  @GetMapping(value = "/allActivities")
  public List<UserActivity> getActivities() {
    return activityService.findAll();
  }

  /**
   * This method accepts a string that represents the date of the activity that should be deleted.
   * @param date a string that represents the date the activity occurred
   */
  @DeleteMapping(value = "/byDate/{date}")
  public void deleteActivityByDate(@PathVariable String date) {
    if (!ObjectUtils.isEmpty(date)) {
      activityService.deleteByDate(date);
      return;
    }
    throw new MissingParameterException("Missing required parameter 'date'");
  }
}
